### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by NPadrutt** [robdavey555/Blazor.ApplicationInsights#3]
In the ReadMe the entry for the Import is: 

`@using Blazor.ApplicationInsights.Components `

But as far as I see it should be:

`@using Blazed.ApplicationInsights.Components `

**Comment by robdavey555** [comment]
Hi @NPadrutt 

Thanks for pointing that out. I had to change the namespace as `Blazor `is reserved in Nuget and I missed this change to the documentation.

I have made the change to the documentation now.

All the best and I hope you find this useful.

Rob

**Comment by NPadrutt** [comment]
Thanks! :)
