### ISSUE TITLE
Logging for navigated not working

### ISSUE THREAD

**Issue by sven5** [robdavey555/Blazor.ApplicationInsights#5]
Hi,

your navigate function has a bug. It only shows `Navigated: ${href}` in console window.
You must use backticks when using Template Strings in js. See reference [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings).

**Comment by robdavey555** [comment]
@sven5 Thanks for spotting

**Comment by sven5** [comment]
@robdavey555 
You should also update the backticks in 
https://github.com/robdavey555/Blazed.ApplicationInsights/blob/master/Blazed.ApplicationInsights/wwwroot/blazor-application-insight.js

Or - if this is autogenerated then please re-generate and check in. 

😄
